// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// cachedaydataDao is the data access object for table cachedaydata.
// You can define custom methods on it to extend its functionality as you wish.
type cachedaydataDao struct {
	*internal.CachedaydataDao
}

var (
	// Cachedaydata is globally public accessible object for table cachedaydata operations.
	Cachedaydata = cachedaydataDao{
		internal.NewCachedaydataDao(),
	}
)

// Fill with you ideas below.
