// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// cachemonthdataDao is the data access object for table cachemonthdata.
// You can define custom methods on it to extend its functionality as you wish.
type cachemonthdataDao struct {
	*internal.CachemonthdataDao
}

var (
	// Cachemonthdata is globally public accessible object for table cachemonthdata operations.
	Cachemonthdata = cachemonthdataDao{
		internal.NewCachemonthdataDao(),
	}
)

// Fill with you ideas below.
