// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// cachedatadayDao is the data access object for table cachedataday.
// You can define custom methods on it to extend its functionality as you wish.
type cachedatadayDao struct {
	*internal.CachedatadayDao
}

var (
	// Cachedataday is globally public accessible object for table cachedataday operations.
	Cachedataday = cachedatadayDao{
		internal.NewCachedatadayDao(),
	}
)

// Fill with you ideas below.
