// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// cachedatamonthDao is the data access object for table cachedatamonth.
// You can define custom methods on it to extend its functionality as you wish.
type cachedatamonthDao struct {
	*internal.CachedatamonthDao
}

var (
	// Cachedatamonth is globally public accessible object for table cachedatamonth operations.
	Cachedatamonth = cachedatamonthDao{
		internal.NewCachedatamonthDao(),
	}
)

// Fill with you ideas below.
