// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// newrolelogDao is the data access object for table newrolelog.
// You can define custom methods on it to extend its functionality as you wish.
type newrolelogDao struct {
	*internal.NewrolelogDao
}

var (
	// Newrolelog is globally public accessible object for table newrolelog operations.
	Newrolelog = newrolelogDao{
		internal.NewNewrolelogDao(),
	}
)

// Fill with you ideas below.
