// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// orderinfoDao is the data access object for table orderinfo.
// You can define custom methods on it to extend its functionality as you wish.
type orderinfoDao struct {
	*internal.OrderinfoDao
}

var (
	// Orderinfo is globally public accessible object for table orderinfo operations.
	Orderinfo = orderinfoDao{
		internal.NewOrderinfoDao(),
	}
)

// Fill with you ideas below.
