// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// platauthorityDao is the data access object for table platauthority.
// You can define custom methods on it to extend its functionality as you wish.
type platauthorityDao struct {
	*internal.PlatauthorityDao
}

var (
	// Platauthority is globally public accessible object for table platauthority operations.
	Platauthority = platauthorityDao{
		internal.NewPlatauthorityDao(),
	}
)

// Fill with you ideas below.
