// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// platbindsDao is the data access object for table platbinds.
// You can define custom methods on it to extend its functionality as you wish.
type platbindsDao struct {
	*internal.PlatbindsDao
}

var (
	// Platbinds is globally public accessible object for table platbinds operations.
	Platbinds = platbindsDao{
		internal.NewPlatbindsDao(),
	}
)

// Fill with you ideas below.
