// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryRoleonlineDao is the data access object for table roleonline.
// You can define custom methods on it to extend its functionality as you wish.
type primaryRoleonlineDao struct {
	*internal.PrimaryRoleonlineDao
}

var (
	// PrimaryRoleonline is globally public accessible object for table roleonline operations.
	PrimaryRoleonline = primaryRoleonlineDao{
		internal.NewPrimaryRoleonlineDao(),
	}
)

// Fill with you ideas below.
