// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryCachemonthdataDao is the data access object for table cachemonthdata.
// You can define custom methods on it to extend its functionality as you wish.
type primaryCachemonthdataDao struct {
	*internal.PrimaryCachemonthdataDao
}

var (
	// PrimaryCachemonthdata is globally public accessible object for table cachemonthdata operations.
	PrimaryCachemonthdata = primaryCachemonthdataDao{
		internal.NewPrimaryCachemonthdataDao(),
	}
)

// Fill with you ideas below.
