// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryCachedaydataDao is the data access object for table cachedaydata.
// You can define custom methods on it to extend its functionality as you wish.
type primaryCachedaydataDao struct {
	*internal.PrimaryCachedaydataDao
}

var (
	// PrimaryCachedaydata is globally public accessible object for table cachedaydata operations.
	PrimaryCachedaydata = primaryCachedaydataDao{
		internal.NewPrimaryCachedaydataDao(),
	}
)

// Fill with you ideas below.
