// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryServerbindsDao is the data access object for table serverbinds.
// You can define custom methods on it to extend its functionality as you wish.
type primaryServerbindsDao struct {
	*internal.PrimaryServerbindsDao
}

var (
	// PrimaryServerbinds is globally public accessible object for table serverbinds operations.
	PrimaryServerbinds = primaryServerbindsDao{
		internal.NewPrimaryServerbindsDao(),
	}
)

// Fill with you ideas below.
