// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryPlatauthorityDao is the data access object for table platauthority.
// You can define custom methods on it to extend its functionality as you wish.
type primaryPlatauthorityDao struct {
	*internal.PrimaryPlatauthorityDao
}

var (
	// PrimaryPlatauthority is globally public accessible object for table platauthority operations.
	PrimaryPlatauthority = primaryPlatauthorityDao{
		internal.NewPrimaryPlatauthorityDao(),
	}
)

// Fill with you ideas below.
