// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryPlatnumberDao is the data access object for table platnumber.
// You can define custom methods on it to extend its functionality as you wish.
type primaryPlatnumberDao struct {
	*internal.PrimaryPlatnumberDao
}

var (
	// PrimaryPlatnumber is globally public accessible object for table platnumber operations.
	PrimaryPlatnumber = primaryPlatnumberDao{
		internal.NewPrimaryPlatnumberDao(),
	}
)

// Fill with you ideas below.
