// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryOrderinfoDao is the data access object for table orderinfo.
// You can define custom methods on it to extend its functionality as you wish.
type primaryOrderinfoDao struct {
	*internal.PrimaryOrderinfoDao
}

var (
	// PrimaryOrderinfo is globally public accessible object for table orderinfo operations.
	PrimaryOrderinfo = primaryOrderinfoDao{
		internal.NewPrimaryOrderinfoDao(),
	}
)

// Fill with you ideas below.
