// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryCachedatamonthDao is the data access object for table cachedatamonth.
// You can define custom methods on it to extend its functionality as you wish.
type primaryCachedatamonthDao struct {
	*internal.PrimaryCachedatamonthDao
}

var (
	// PrimaryCachedatamonth is globally public accessible object for table cachedatamonth operations.
	PrimaryCachedatamonth = primaryCachedatamonthDao{
		internal.NewPrimaryCachedatamonthDao(),
	}
)

// Fill with you ideas below.
