// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryNewrolelogDao is the data access object for table newrolelog.
// You can define custom methods on it to extend its functionality as you wish.
type primaryNewrolelogDao struct {
	*internal.PrimaryNewrolelogDao
}

var (
	// PrimaryNewrolelog is globally public accessible object for table newrolelog operations.
	PrimaryNewrolelog = primaryNewrolelogDao{
		internal.NewPrimaryNewrolelogDao(),
	}
)

// Fill with you ideas below.
