// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryServerconfigDao is the data access object for table serverconfig.
// You can define custom methods on it to extend its functionality as you wish.
type primaryServerconfigDao struct {
	*internal.PrimaryServerconfigDao
}

var (
	// PrimaryServerconfig is globally public accessible object for table serverconfig operations.
	PrimaryServerconfig = primaryServerconfigDao{
		internal.NewPrimaryServerconfigDao(),
	}
)

// Fill with you ideas below.
