// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryPlatbindsDao is the data access object for table platbinds.
// You can define custom methods on it to extend its functionality as you wish.
type primaryPlatbindsDao struct {
	*internal.PrimaryPlatbindsDao
}

var (
	// PrimaryPlatbinds is globally public accessible object for table platbinds operations.
	PrimaryPlatbinds = primaryPlatbindsDao{
		internal.NewPrimaryPlatbindsDao(),
	}
)

// Fill with you ideas below.
