// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryServertagDao is the data access object for table servertag.
// You can define custom methods on it to extend its functionality as you wish.
type primaryServertagDao struct {
	*internal.PrimaryServertagDao
}

var (
	// PrimaryServertag is globally public accessible object for table servertag operations.
	PrimaryServertag = primaryServertagDao{
		internal.NewPrimaryServertagDao(),
	}
)

// Fill with you ideas below.
