// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// primaryCachedatadayDao is the data access object for table cachedataday.
// You can define custom methods on it to extend its functionality as you wish.
type primaryCachedatadayDao struct {
	*internal.PrimaryCachedatadayDao
}

var (
	// PrimaryCachedataday is globally public accessible object for table cachedataday operations.
	PrimaryCachedataday = primaryCachedatadayDao{
		internal.NewPrimaryCachedatadayDao(),
	}
)

// Fill with you ideas below.
