// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// roleonlineDao is the data access object for table roleonline.
// You can define custom methods on it to extend its functionality as you wish.
type roleonlineDao struct {
	*internal.RoleonlineDao
}

var (
	// Roleonline is globally public accessible object for table roleonline operations.
	Roleonline = roleonlineDao{
		internal.NewRoleonlineDao(),
	}
)

// Fill with you ideas below.
