// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// serverconfigDao is the data access object for table serverconfig.
// You can define custom methods on it to extend its functionality as you wish.
type serverconfigDao struct {
	*internal.ServerconfigDao
}

var (
	// Serverconfig is globally public accessible object for table serverconfig operations.
	Serverconfig = serverconfigDao{
		internal.NewServerconfigDao(),
	}
)

// Fill with you ideas below.
