// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// servertagDao is the data access object for table servertag.
// You can define custom methods on it to extend its functionality as you wish.
type servertagDao struct {
	*internal.ServertagDao
}

var (
	// Servertag is globally public accessible object for table servertag operations.
	Servertag = servertagDao{
		internal.NewServertagDao(),
	}
)

// Fill with you ideas below.
