// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// serverbindsDao is the data access object for table serverbinds.
// You can define custom methods on it to extend its functionality as you wish.
type serverbindsDao struct {
	*internal.ServerbindsDao
}

var (
	// Serverbinds is globally public accessible object for table serverbinds operations.
	Serverbinds = serverbindsDao{
		internal.NewServerbindsDao(),
	}
)

// Fill with you ideas below.
