// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PlatauthorityDao is the data access object for table platauthority.
type PlatauthorityDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns PlatauthorityColumns // columns contains all the column names of Table for convenient usage.
}

// PlatauthorityColumns defines and stores column names for table platauthority.
type PlatauthorityColumns struct {
	Platflag string // 渠道名称_英文
	Platcid  string // 大平台
	Platnid  string // 渠道ID
}

// platauthorityColumns holds the columns for table platauthority.
var platauthorityColumns = PlatauthorityColumns{
	Platflag: "platflag",
	Platcid:  "platcid",
	Platnid:  "platnid",
}

// NewPlatauthorityDao creates and returns a new DAO object for table data access.
func NewPlatauthorityDao() *PlatauthorityDao {
	return &PlatauthorityDao{
		group:   "default",
		table:   "platauthority",
		columns: platauthorityColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PlatauthorityDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PlatauthorityDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PlatauthorityDao) Columns() PlatauthorityColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PlatauthorityDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PlatauthorityDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PlatauthorityDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
