// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PlatbindsDao is the data access object for table platbinds.
type PlatbindsDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns PlatbindsColumns // columns contains all the column names of Table for convenient usage.
}

// PlatbindsColumns defines and stores column names for table platbinds.
type PlatbindsColumns struct {
	Platcid string // 渠道ID
	Platnid string // 渠道号
}

// platbindsColumns holds the columns for table platbinds.
var platbindsColumns = PlatbindsColumns{
	Platcid: "platcid",
	Platnid: "platnid",
}

// NewPlatbindsDao creates and returns a new DAO object for table data access.
func NewPlatbindsDao() *PlatbindsDao {
	return &PlatbindsDao{
		group:   "default",
		table:   "platbinds",
		columns: platbindsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PlatbindsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PlatbindsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PlatbindsDao) Columns() PlatbindsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PlatbindsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PlatbindsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PlatbindsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
