// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryPlatbindsDao is the data access object for table platbinds.
type PrimaryPlatbindsDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns PrimaryPlatbindsColumns // columns contains all the column names of Table for convenient usage.
}

// PrimaryPlatbindsColumns defines and stores column names for table platbinds.
type PrimaryPlatbindsColumns struct {
	Platcid string // 渠道ID
	Platnid string // 渠道号
}

// primaryPlatbindsColumns holds the columns for table platbinds.
var primaryPlatbindsColumns = PrimaryPlatbindsColumns{
	Platcid: "platcid",
	Platnid: "platnid",
}

// NewPrimaryPlatbindsDao creates and returns a new DAO object for table data access.
func NewPrimaryPlatbindsDao() *PrimaryPlatbindsDao {
	return &PrimaryPlatbindsDao{
		group:   "default",
		table:   "platbinds",
		columns: primaryPlatbindsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrimaryPlatbindsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrimaryPlatbindsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrimaryPlatbindsDao) Columns() PrimaryPlatbindsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrimaryPlatbindsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrimaryPlatbindsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrimaryPlatbindsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
