// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryServertagDao is the data access object for table servertag.
type PrimaryServertagDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns PrimaryServertagColumns // columns contains all the column names of Table for convenient usage.
}

// PrimaryServertagColumns defines and stores column names for table servertag.
type PrimaryServertagColumns struct {
	Tagid     string // 标签ID
	TagnameCN string // 标签显示名称
	TagnameEN string // 标签显示名称
	Descript  string // 描述信息
	Valid     string // 是否有效
}

// primaryServertagColumns holds the columns for table servertag.
var primaryServertagColumns = PrimaryServertagColumns{
	Tagid:     "tagid",
	TagnameCN: "tagname_CN",
	TagnameEN: "tagname_EN",
	Descript:  "descript",
	Valid:     "valid",
}

// NewPrimaryServertagDao creates and returns a new DAO object for table data access.
func NewPrimaryServertagDao() *PrimaryServertagDao {
	return &PrimaryServertagDao{
		group:   "default",
		table:   "servertag",
		columns: primaryServertagColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrimaryServertagDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrimaryServertagDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrimaryServertagDao) Columns() PrimaryServertagColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrimaryServertagDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrimaryServertagDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrimaryServertagDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
