// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryPlatconfigDao is the data access object for table platconfig.
type PrimaryPlatconfigDao struct {
	table   string                   // table is the underlying table name of the DAO.
	group   string                   // group is the database configuration group name of current DAO.
	columns PrimaryPlatconfigColumns // columns contains all the column names of Table for convenient usage.
}

// PrimaryPlatconfigColumns defines and stores column names for table platconfig.
type PrimaryPlatconfigColumns struct {
	Platcid   string // 渠道ID
	CnameCN   string // 渠道名称_中文
	CnameEN   string // 渠道名称_英文
	Cdescript string // 描述信息
	Cvalid    string // 是否有效
}

// primaryPlatconfigColumns holds the columns for table platconfig.
var primaryPlatconfigColumns = PrimaryPlatconfigColumns{
	Platcid:   "platcid",
	CnameCN:   "cname_CN",
	CnameEN:   "cname_EN",
	Cdescript: "cdescript",
	Cvalid:    "cvalid",
}

// NewPrimaryPlatconfigDao creates and returns a new DAO object for table data access.
func NewPrimaryPlatconfigDao() *PrimaryPlatconfigDao {
	return &PrimaryPlatconfigDao{
		group:   "default",
		table:   "platconfig",
		columns: primaryPlatconfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrimaryPlatconfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrimaryPlatconfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrimaryPlatconfigDao) Columns() PrimaryPlatconfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrimaryPlatconfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrimaryPlatconfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrimaryPlatconfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
