// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryServerconfigDao is the data access object for table serverconfig.
type PrimaryServerconfigDao struct {
	table   string                     // table is the underlying table name of the DAO.
	group   string                     // group is the database configuration group name of current DAO.
	columns PrimaryServerconfigColumns // columns contains all the column names of Table for convenient usage.
}

// PrimaryServerconfigColumns defines and stores column names for table serverconfig.
type PrimaryServerconfigColumns struct {
	Serverid string // 服务ID
	NameCN   string // 显示名称_中文
	NameEN   string // 显示名称_英文
	Descript string // 描述信息
	Ctime    string // 服务器创建时间
	Valid    string // 是否有效
}

// primaryServerconfigColumns holds the columns for table serverconfig.
var primaryServerconfigColumns = PrimaryServerconfigColumns{
	Serverid: "serverid",
	NameCN:   "name_CN",
	NameEN:   "name_EN",
	Descript: "descript",
	Ctime:    "ctime",
	Valid:    "valid",
}

// NewPrimaryServerconfigDao creates and returns a new DAO object for table data access.
func NewPrimaryServerconfigDao() *PrimaryServerconfigDao {
	return &PrimaryServerconfigDao{
		group:   "default",
		table:   "serverconfig",
		columns: primaryServerconfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrimaryServerconfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrimaryServerconfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrimaryServerconfigDao) Columns() PrimaryServerconfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrimaryServerconfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrimaryServerconfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrimaryServerconfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
