// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryServerbindsDao is the data access object for table serverbinds.
type PrimaryServerbindsDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns PrimaryServerbindsColumns // columns contains all the column names of Table for convenient usage.
}

// PrimaryServerbindsColumns defines and stores column names for table serverbinds.
type PrimaryServerbindsColumns struct {
	Serverid string // 服务ID
	Tagid    string // 服务标签
}

// primaryServerbindsColumns holds the columns for table serverbinds.
var primaryServerbindsColumns = PrimaryServerbindsColumns{
	Serverid: "serverid",
	Tagid:    "tagid",
}

// NewPrimaryServerbindsDao creates and returns a new DAO object for table data access.
func NewPrimaryServerbindsDao() *PrimaryServerbindsDao {
	return &PrimaryServerbindsDao{
		group:   "default",
		table:   "serverbinds",
		columns: primaryServerbindsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrimaryServerbindsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrimaryServerbindsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrimaryServerbindsDao) Columns() PrimaryServerbindsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrimaryServerbindsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrimaryServerbindsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrimaryServerbindsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
