// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RoleonlineDao is the data access object for table roleonline.
type RoleonlineDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns RoleonlineColumns // columns contains all the column names of Table for convenient usage.
}

// RoleonlineColumns defines and stores column names for table roleonline.
type RoleonlineColumns struct {
	Roleid   string // 角色id
	Serverid string // 服务ID
	Platn    string // 角色渠道
	Ctime    string // 最近一次上线时间
	Day      string // 最近一次上线时间day
	Month    string // 最近一次上线时间month
}

// roleonlineColumns holds the columns for table roleonline.
var roleonlineColumns = RoleonlineColumns{
	Roleid:   "roleid",
	Serverid: "serverid",
	Platn:    "platn",
	Ctime:    "ctime",
	Day:      "day",
	Month:    "month",
}

// NewRoleonlineDao creates and returns a new DAO object for table data access.
func NewRoleonlineDao() *RoleonlineDao {
	return &RoleonlineDao{
		group:   "default",
		table:   "roleonline",
		columns: roleonlineColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RoleonlineDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RoleonlineDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RoleonlineDao) Columns() RoleonlineColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RoleonlineDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RoleonlineDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RoleonlineDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
