// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ServerconfigDao is the data access object for table serverconfig.
type ServerconfigDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns ServerconfigColumns // columns contains all the column names of Table for convenient usage.
}

// ServerconfigColumns defines and stores column names for table serverconfig.
type ServerconfigColumns struct {
	Serverid string // 服务ID
	NameCN   string // 显示名称_中文
	NameEN   string // 显示名称_英文
	Descript string // 描述信息
	Ctime    string // 服务器创建时间
	Valid    string // 是否有效
}

// serverconfigColumns holds the columns for table serverconfig.
var serverconfigColumns = ServerconfigColumns{
	Serverid: "serverid",
	NameCN:   "name_CN",
	NameEN:   "name_EN",
	Descript: "descript",
	Ctime:    "ctime",
	Valid:    "valid",
}

// NewServerconfigDao creates and returns a new DAO object for table data access.
func NewServerconfigDao() *ServerconfigDao {
	return &ServerconfigDao{
		group:   "default",
		table:   "serverconfig",
		columns: serverconfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ServerconfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ServerconfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ServerconfigDao) Columns() ServerconfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ServerconfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ServerconfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ServerconfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
