// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ServertagDao is the data access object for table servertag.
type ServertagDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns ServertagColumns // columns contains all the column names of Table for convenient usage.
}

// ServertagColumns defines and stores column names for table servertag.
type ServertagColumns struct {
	Tagid     string // 标签ID
	TagnameCN string // 标签显示名称
	TagnameEN string // 标签显示名称
	Descript  string // 描述信息
	Valid     string // 是否有效
}

// servertagColumns holds the columns for table servertag.
var servertagColumns = ServertagColumns{
	Tagid:     "tagid",
	TagnameCN: "tagname_CN",
	TagnameEN: "tagname_EN",
	Descript:  "descript",
	Valid:     "valid",
}

// NewServertagDao creates and returns a new DAO object for table data access.
func NewServertagDao() *ServertagDao {
	return &ServertagDao{
		group:   "default",
		table:   "servertag",
		columns: servertagColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ServertagDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ServertagDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ServertagDao) Columns() ServertagColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ServertagDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ServertagDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ServertagDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
