// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Cachedatamonth is the golang structure of table cachedatamonth for DAO operations like Where/Data.
type Cachedatamonth struct {
	g.Meta      `orm:"table:cachedatamonth, do:true"`
	Serverid    interface{} // 服务ID
	Platn       interface{} // 角色渠道
	Roletotal   interface{} // 月总用户
	TotalDau    interface{} // 月(每日)总活跃
	Month       interface{} // month
	Mau         interface{} // 月活跃MAU
	Newrole     interface{} // 新用户
	Payroles    interface{} // 当日付费用户数
	PaymoneyCny interface{} // 当日付费总金额_人民币
	PaymoneyEny interface{} // 当日付费总金额_美元
}
