// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Cachedaydata is the golang structure of table cachedaydata for DAO operations like Where/Data.
type Cachedaydata struct {
	g.Meta   `orm:"table:cachedaydata, do:true"`
	Serverid interface{} // 服务ID
	Platn    interface{} // 角色渠道
	Day      interface{} // day
	Dau      interface{} // 日活跃
}
