// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Orderinfo is the golang structure of table orderinfo for DAO operations like Where/Data.
type Orderinfo struct {
	g.Meta      `orm:"table:orderinfo, do:true"`
	Orderid     interface{} // 订单id
	Serverid    interface{} // 服务ID
	Platn       interface{} // 角色渠道
	Roleid      interface{} // 角色ID
	Goodsid     interface{} // 商品ID
	PaymoneyCNY interface{} // 充值金额_人民币
	PaymoneyUSD interface{} // 充值金额_美元
	Currency    interface{} // 币种
	Ctime       *gtime.Time // 订单时间
	Day         interface{} // 订单时间day
	Hour        interface{} // 订单时间hour
	Month       interface{} // 订单时间month
}
