// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Platbinds is the golang structure of table platbinds for DAO operations like Where/Data.
type Platbinds struct {
	g.Meta  `orm:"table:platbinds, do:true"`
	Platcid interface{} // 渠道ID
	Platnid interface{} // 渠道号
}
