// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Platnumber is the golang structure of table platnumber for DAO operations like Where/Data.
type Platnumber struct {
	g.Meta    `orm:"table:platnumber, do:true"`
	Platnid   interface{} // 渠道号ID
	Platn     interface{} // 渠道号
	NnameCN   interface{} // 显示名称_中文
	NnameEN   interface{} // 显示名称_英文
	Ndescript interface{} // 描述信息
	Nvalid    interface{} // 是否有效
}
