// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryServerbinds is the golang structure of table serverbinds for DAO operations like Where/Data.
type PrimaryServerbinds struct {
	g.Meta   `orm:"table:serverbinds, do:true"`
	Serverid interface{} // 服务ID
	Tagid    interface{} // 服务标签
}
