// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PrimaryNewrolelog is the golang structure of table newrolelog for DAO operations like Where/Data.
type PrimaryNewrolelog struct {
	g.Meta   `orm:"table:newrolelog, do:true"`
	Roleid   interface{} // 角色id
	Serverid interface{} // 服务ID
	Platn    interface{} // 角色渠道
	Ctime    *gtime.Time // 创建时间
	Day      interface{} // 创建时间day
	Hour     interface{} // 创建时间hour
	Month    interface{} // 创建时间month
}
