// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryCachemonthdata is the golang structure of table cachemonthdata for DAO operations like Where/Data.
type PrimaryCachemonthdata struct {
	g.Meta   `orm:"table:cachemonthdata, do:true"`
	Serverid interface{} // 服务ID
	Platn    interface{} // 角色渠道
	Month    interface{} // month
	Mau      interface{} // 月活跃MAU
}
