// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryServertag is the golang structure of table servertag for DAO operations like Where/Data.
type PrimaryServertag struct {
	g.Meta    `orm:"table:servertag, do:true"`
	Tagid     interface{} // 标签ID
	TagnameCN interface{} // 标签显示名称
	TagnameEN interface{} // 标签显示名称
	Descript  interface{} // 描述信息
	Valid     interface{} // 是否有效
}
