// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryCachedataday is the golang structure of table cachedataday for DAO operations like Where/Data.
type PrimaryCachedataday struct {
	g.Meta         `orm:"table:cachedataday, do:true"`
	Serverid       interface{} // 服务ID
	Platn          interface{} // 角色渠道
	Day            interface{} // day
	Dau            interface{} // 日活跃
	Newrolecount   interface{} // 新用户
	Payroles       interface{} // 当日付费用户数
	PaymoneyCny    interface{} // 当日付费总金额_人民币
	PaymoneyEny    interface{} // 当日付费总金额_美元
	Newpayroles    interface{} // 当日新用户付费数
	NewpaymoneyCny interface{} // 当日新用户付费总金额_人民币
	NewpaymoneyEny interface{} // 当日新用户付费总金额_美元
}
