// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryPlatconfig is the golang structure of table platconfig for DAO operations like Where/Data.
type PrimaryPlatconfig struct {
	g.Meta    `orm:"table:platconfig, do:true"`
	Platcid   interface{} // 渠道ID
	CnameCN   interface{} // 渠道名称_中文
	CnameEN   interface{} // 渠道名称_英文
	Cdescript interface{} // 描述信息
	Cvalid    interface{} // 是否有效
}
