// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryPlatbinds is the golang structure of table platbinds for DAO operations like Where/Data.
type PrimaryPlatbinds struct {
	g.Meta  `orm:"table:platbinds, do:true"`
	Platcid interface{} // 渠道ID
	Platnid interface{} // 渠道号
}
