// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrimaryPlatauthority is the golang structure of table platauthority for DAO operations like Where/Data.
type PrimaryPlatauthority struct {
	g.Meta   `orm:"table:platauthority, do:true"`
	Platflag interface{} // 渠道名称_英文
	Platcid  interface{} // 大平台
	Platnid  interface{} // 渠道ID
}
