// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Roleonline is the golang structure of table roleonline for DAO operations like Where/Data.
type Roleonline struct {
	g.Meta   `orm:"table:roleonline, do:true"`
	Roleid   interface{} // 角色id
	Serverid interface{} // 服务ID
	Platn    interface{} // 角色渠道
	Ctime    *gtime.Time // 最近一次上线时间
	Day      interface{} // 最近一次上线时间day
	Month    interface{} // 最近一次上线时间month
}
