// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Serverbinds is the golang structure of table serverbinds for DAO operations like Where/Data.
type Serverbinds struct {
	g.Meta   `orm:"table:serverbinds, do:true"`
	Serverid interface{} // 服务ID
	Tagid    interface{} // 服务标签
}
