server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true
  path: "./tract"
  ctxKeys: []
database:
  default:
    link: "mysql:root:@tcp(localhost:3306)/bitest"

gfcli:
  gen:
    dao:
      - link: "mysql:root:@tcp(localhost:3306)/bitest"



