server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true
  path: "./tract"
  ctxKeys: []


gfcli:
  gen:
    dao:
      - link:   "mysql:tcnewbi:rE4]Y_Lg3e@tcp(10.0.0.10:3307)/tcnewbi"
        prefix: "primary_"



