// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Cachemonthdata is the golang structure for table cachemonthdata.
type Cachemonthdata struct {
	Serverid int    `json:"serverid" ` // 服务ID
	Platn    string `json:"platn"    ` // 角色渠道
	Month    int    `json:"month"    ` // month
	Mau      int    `json:"mau"      ` // 月活跃MAU
}
