// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Cachedaydata is the golang structure for table cachedaydata.
type Cachedaydata struct {
	Serverid int    `json:"serverid" ` // 服务ID
	Platn    string `json:"platn"    ` // 角色渠道
	Day      int    `json:"day"      ` // day
	Dau      int    `json:"dau"      ` // 日活跃
}
