// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Platauthority is the golang structure for table platauthority.
type Platauthority struct {
	Platflag string `json:"platflag" ` // 渠道名称_英文
	Platcid  int    `json:"platcid"  ` // 大平台
	Platnid  int    `json:"platnid"  ` // 渠道ID
}
