// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Platbinds is the golang structure for table platbinds.
type Platbinds struct {
	Platcid int `json:"platcid" ` // 渠道ID
	Platnid int `json:"platnid" ` // 渠道号
}
