// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Platconfig is the golang structure for table platconfig.
type Platconfig struct {
	Platcid   int    `json:"platcid"   ` // 渠道ID
	CnameCN   string `json:"cnameCN"   ` // 渠道名称_中文
	CnameEN   string `json:"cnameEN"   ` // 渠道名称_英文
	Cdescript string `json:"cdescript" ` // 描述信息
	Cvalid    int    `json:"cvalid"    ` // 是否有效
}
