// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Platnumber is the golang structure for table platnumber.
type Platnumber struct {
	Platnid   int    `json:"platnid"   ` // 渠道号ID
	Platn     string `json:"platn"     ` // 渠道号
	NnameCN   string `json:"nnameCN"   ` // 显示名称_中文
	NnameEN   string `json:"nnameEN"   ` // 显示名称_英文
	Ndescript string `json:"ndescript" ` // 描述信息
	Nvalid    int    `json:"nvalid"    ` // 是否有效
}
