// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryServerbinds is the golang structure for table primary_serverbinds.
type PrimaryServerbinds struct {
	Serverid int `json:"serverid" ` // 服务ID
	Tagid    int `json:"tagid"    ` // 服务标签
}
