// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PrimaryServerconfig is the golang structure for table primary_serverconfig.
type PrimaryServerconfig struct {
	Serverid int         `json:"serverid" ` // 服务ID
	NameCN   string      `json:"nameCN"   ` // 显示名称_中文
	NameEN   string      `json:"nameEN"   ` // 显示名称_英文
	Descript string      `json:"descript" ` // 描述信息
	Ctime    *gtime.Time `json:"ctime"    ` // 服务器创建时间
	Valid    int         `json:"valid"    ` // 是否有效
}
