// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryServertag is the golang structure for table primary_servertag.
type PrimaryServertag struct {
	Tagid     int    `json:"tagid"     ` // 标签ID
	TagnameCN string `json:"tagnameCN" ` // 标签显示名称
	TagnameEN string `json:"tagnameEN" ` // 标签显示名称
	Descript  string `json:"descript"  ` // 描述信息
	Valid     int    `json:"valid"     ` // 是否有效
}
