// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryPlatauthority is the golang structure for table primary_platauthority.
type PrimaryPlatauthority struct {
	Platflag string `json:"platflag" ` // 渠道名称_英文
	Platcid  int    `json:"platcid"  ` // 大平台
	Platnid  int    `json:"platnid"  ` // 渠道ID
}
