// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryPlatbinds is the golang structure for table primary_platbinds.
type PrimaryPlatbinds struct {
	Platcid int `json:"platcid" ` // 渠道ID
	Platnid int `json:"platnid" ` // 渠道号
}
