// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryCachemonthdata is the golang structure for table primary_cachemonthdata.
type PrimaryCachemonthdata struct {
	Serverid int    `json:"serverid" ` // 服务ID
	Platn    string `json:"platn"    ` // 角色渠道
	Month    int    `json:"month"    ` // month
	Mau      int    `json:"mau"      ` // 月活跃MAU
}
