// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-16 10:18:26
// =================================================================================

package entity

// PrimaryCachedatamonth is the golang structure for table primary_cachedatamonth.
type PrimaryCachedatamonth struct {
	Serverid    int    `json:"serverid"    ` // 服务ID
	Platn       string `json:"platn"       ` // 角色渠道
	Roletotal   int    `json:"roletotal"   ` // 月总用户
	TotalDau    int    `json:"totalDau"    ` // 月(每日)总活跃
	Month       int    `json:"month"       ` // month
	Mau         int    `json:"mau"         ` // 月活跃MAU
	Newrole     int    `json:"newrole"     ` // 新用户
	Payroles    int    `json:"payroles"    ` // 当日付费用户数
	PaymoneyCny int    `json:"paymoneyCny" ` // 当日付费总金额_人民币
	PaymoneyEny int    `json:"paymoneyEny" ` // 当日付费总金额_美元
}
