// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Roleonline is the golang structure for table roleonline.
type Roleonline struct {
	Roleid   int64       `json:"roleid"   ` // 角色id
	Serverid int         `json:"serverid" ` // 服务ID
	Platn    string      `json:"platn"    ` // 角色渠道
	Ctime    *gtime.Time `json:"ctime"    ` // 最近一次上线时间
	Day      int         `json:"day"      ` // 最近一次上线时间day
	Month    int         `json:"month"    ` // 最近一次上线时间month
}
