// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Serverbinds is the golang structure for table serverbinds.
type Serverbinds struct {
	Serverid int `json:"serverid" ` // 服务ID
	Tagid    int `json:"tagid"    ` // 服务标签
}
