// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-09-19 15:24:37
// =================================================================================

package entity

// Servertag is the golang structure for table servertag.
type Servertag struct {
	Tagid     int    `json:"tagid"     ` // 标签ID
	TagnameCN string `json:"tagnameCN" ` // 标签显示名称
	TagnameEN string `json:"tagnameEN" ` // 标签显示名称
	Descript  string `json:"descript"  ` // 描述信息
	Valid     int    `json:"valid"     ` // 是否有效
}
